### ISSUE TITLE
Save more data in the filename

### ISSUE THREAD

**Issue by nozoku** [Emperorlou/MidJourneyTools#1]
It would be great if it would be possible to save the full prompt in the filename as well as the original date when the image was generated by MidJourney (prompt is available when you hover over the image, date AFAIK only when you click the image).

Thanks for a great tool!

**Comment by Emperorlou** [comment]
At this point I don't think this will be possible simply because we are triggering MidJourney's own save button in the UI to perform the save operation. I did try downloading the image and saving it (after converting it to jpg or png) but cross-domain issues prevented me from doing this successfully. I'm afraid I don't think this is possible under the current saving mechanism. If someone wants to give saving from a canvas another shot, maybe there is some magic I don't know about!

**Comment by nozoku** [comment]
Don't know if it's possible, but maybe there is a way to rename the saved file?

**Comment by Emperorlou** [comment]
I don't think so... but a deeper dive would have to be done to confirm it.
It depends on how they name the file to begin with. Likely the only way to
accomplish it would be to try to augment the javascript code used to save
it in the first place and that's going to be almost impossible as they use
React and the code is probably heavily obfuscated.

**Comment by vinyvince** [comment]
Obviously, it's pity. It's my main "issue" with this script, i mean limitation. Is it not possible to run two loop in parallel one to save the image and one to save all string description in each image sub page or kind of... and associate both structures after? 
Off course it will take longer, but it's really important. Prompt are as or more precious as the result

Thanks you, for this neat tool

**Comment by johnthethird** [comment]
I have a **very** hacky workaround here:  https://github.com/Emperorlou/MidJourneyTools/pull/2

**Comment by Emperorlou** [comment]
Thanks to @johnthethird, we just released a new version (1.3.0) that includes a handy checkbox for those who want to download the FULL prompt that was used to generate each image. Now, with this new option turned on, every image you download from the gallery will include a .txt file beside it (with the same name as the image) that contains the full prompt that was used to generate that image.
